Update rclone-backup-tool

diff --git a/rclone-backup-tool b/rclone-backup-tool
--- a/rclone-backup-tool
+++ b/rclone-backup-tool
@@ -31,6 +31,11 @@ archives=$(find $1 -maxdepth 1 -not -type d)
 for archive in $archives; do
   md5sum $1/$archive > $archive.md5
   rclone sync -v $1/$archive.md5 $2:/$FOLDER_NAME/ &>> $FOLDER_NAME.log
+  if [ $? -ne 0 ]
+  then
+    echo "!!! Error in backup file $archive.md5 !!!" >> $FOLDER_NAME.log
+  fi
+
   rclone sync -v $1/$archive $2:/$FOLDER_NAME/ &>> $FOLDER_NAME.log
   if [ $? -ne 0 ]
   then
